### PR TITLE
Fix #76: remove infinite restart when app disabled.

### LINKED ISSUE #76: Infinity error when app disabled
When any team disables/removes application after releasing a bot, it produces `Slack::Web::Api::Error` with `account_inactive` message on logs. After that, server tries to reconnect, which produces the same error, and it is endless.
I found at `/lib/slack-ruby-bot/server.rb:94` potential problem which in fact infinitely restart server without the checking of incoming error type.

### PR DESCRIPTION
**Pull request by SlayerShadow**
Added error checking for `restart!` method on `lib/slack-ruby-bot/server.rb`.

### CODE REVIEW

**Comment by dblock** [comment]
This needs tests, please, and a CHANGELOG entry.

**Comment by SlayerShadow** [comment]
Done. Does it need a new PR?

**Comment by dblock** [comment]
No need for a new PR, keep adding here. Fix [the build](https://travis-ci.org/dblock/slack-ruby-bot/jobs/135072940) next. Probably just `rubocop -a` and `rubocop --auto-gen-config`.

**Comment by SlayerShadow** [comment]
I have 200 offenses detected at `rubocop --auto-gen-config` on untouched files. What's wrong? First command successfully fixed.

**Comment by dblock** [comment]
Merged, thanks! Rubocop shows you violations as if it was a clean run. So nothing is wrong. If you want to address them you would look into the TODO file that it generates.

**Comment by SlayerShadow** [comment]
Ok, Thanks!

**Pull request merged**
