### PR TITLE
Remove weird parsing bit that kills Regex routes.

### PR DESCRIPTION
**Pull request by zachfeldman**
If I leave this in, none of my regex "match" routes seem to work. Any ideas?

### CODE REVIEW

**Comment by dblock** [comment]
It's not that weird. It supports matching the bot name and aliases. Why don't you explain the bug that you're seeing, and, better, write a failing test for it? Happy to help fix.

**Comment by zachfeldman** [comment]
Sure, the bug I'm seeing is when I try to use a custom matcher rather than the `command` syntax (`match`, etc).

It seems that using the existing "parser" function, the regex matching fails because the bot name is appended to my command.

I don't really have time to write a failing test but just thought I'd bring this to your attention! My fork is working fine for me. Good luck!

**Comment by dblock** [comment]
Can you provide an example of the custom matcher?

**Comment by zachfeldman** [comment]
Sure, here's the whole bot:
https://github.com/zachfeldman/done-bot

**Comment by dblock** [comment]
@zachfeldman Would you please try HEAD without this change? Turns out I didn't even have `match` specs, so now that's corrected and the parser is a little smarter. The goal for the non-regex version is to support addressing the bot, it's hacky at best, but with my fix it works in all scenarios looks like.

**Comment by zachfeldman** [comment]
HEAD works!!

**Comment by dblock** [comment]
I released 0.4.5. Thanks for bringing this up.

**Comment by zachfeldman** [comment]
Sweet! Thanks for making such a sweet client to make this easier :)

**Comment by dblock** [comment]
:+1:

**Pull request closed without merging**
