### PR TITLE
Fix RegexpError when parsing command

### PR DESCRIPTION
**Pull request by kuboshizuma**
Regexp error happens when receiving meta character for commands.
This commit makes commands escaped.

### CODE REVIEW

**Comment by kuboshizuma** [comment]
Oops, should we change the settings for RuboCop?

```
lib/slack-ruby-bot/commands/base.rb:3:5: C: Class has too many lines. [101/100]
    class Base
    ^^^^^
62 files inspected, 1 offense detected
RuboCop failed!
```

**Comment by dblock** [comment]
This is great, thanks! Update CHANGELOG please. For RuboCop run `rubocop --auto-gen-config`. Commit via `--amend`.

**Comment by kuboshizuma** [comment]
Thank you for changing settings for RuboCop!
Now, update commit following your comment.

**Comment by dblock** [comment]
Still needs an entry in CHANGELOG, please.

**Comment by kuboshizuma** [comment]
I commit again for CHANGELOG.
Is it all right?

**Comment by dblock** [comment]
Looks great, merging. Thanks.

**Pull request merged**
