### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by knjko**
Minor changes. Is this correct?

### CODE REVIEW

**Comment by dblock** [comment]
Did you make it work? I think this should be an `include` actually.

**Comment by knjko** [comment]
You're right. Fixed :innocent:

**Comment by knjko** [comment]
hmm, it is not necessary to include `SlackRubyBot::Hooks::HookSupport` in hooks??

https://github.com/dblock/slack-ruby-bot/blob/master/lib/slack-ruby-bot/hooks/message.rb
https://github.com/dblock/slack-ruby-bot/blob/master/lib/slack-ruby-bot/server.rb#L21

**Comment by dblock** [comment]
I remember what happened in https://github.com/dblock/slack-ruby-bot/commit/6ff89e5d0c6b7904521433c580e9f98d0b42b44b now, the `Base` class was just removed. Kill this line please?

**Comment by dramalho** [comment]
ahhh dang, my bad!!!!

**Comment by knjko** [comment]
:wink: :scissors:

**Comment by dblock** [comment]
Merged, thank you.

**Pull request merged**
