### PR TITLE
base command parse method refactoring

### PR DESCRIPTION
**Pull request by accessd**
I hope it became more clear :smiley:

### CODE REVIEW

**Comment by dblock** [comment]
It's much better, thanks! 

Can I nitpick, would you mind changing `.try(:method)` into actual checks? I've been diligently avoiding `try` because you can easily make a mistake or the interface underneath changes and you'll never know.

**Comment by dblock** [comment]
Also now that these methods are their own thing you should/could write a couple of specs for them individually.

**Comment by accessd** [comment]
> Can I nitpick, would you mind changing .try(:method) into actual checks? I've been diligently avoiding try because you can easily make a mistake or the interface underneath changes and you'll never know.

So I'm using `try!`
```Same as #try, but will raise a NoMethodError exception if the receiver is not +nil+ and does not implement the tried method.```

But, if it's a some guideline for this repo I can revert to actual checks.

> Also now that these methods are their own thing you should/could write a couple of specs for them individually.

Yep! I'll do it.

**Comment by dblock** [comment]
Lets go old school without `try`, it's really a personal preference, don't hold it against me.

**Comment by accessd** [comment]
Ready!

**Comment by dblock** [comment]
Merged via https://github.com/dblock/slack-ruby-bot/commit/ea25aeec6b45d6e21319c4c95672cec33e18e6b3, thank you!

Class methods cannot be marked `private`, that was wrong in the original code, corrected it and used just regular method calls in the spec. Also changed `eq(true)` to `be true` which is a little more readable.

**Pull request closed without merging**
